"""create catalog tables

Revision ID: 20260806catalog
Revises: 20260806overview
Create Date: 2026-08-06 09:55:43.150241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260806catalog'
down_revision: Union[str, None] = '20260806overview'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_versions_is_active'), 'knowledge_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_knowledge_versions_status'), 'knowledge_versions', ['status'], unique=False)
    op.create_table('quiz_sets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('knowledge_version_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_version_id'], ['knowledge_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_sets_knowledge_version_id'), 'quiz_sets', ['knowledge_version_id'], unique=False)
    op.create_index(op.f('ix_quiz_sets_status'), 'quiz_sets', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('quiz_set_id', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_set_id'], ['quiz_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_quiz_set_id'), 'questions', ['quiz_set_id'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_quiz_set_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_quiz_sets_status'), table_name='quiz_sets')
    op.drop_index(op.f('ix_quiz_sets_knowledge_version_id'), table_name='quiz_sets')
    op.drop_table('quiz_sets')
    op.drop_index(op.f('ix_knowledge_versions_status'), table_name='knowledge_versions')
    op.drop_index(op.f('ix_knowledge_versions_is_active'), table_name='knowledge_versions')
    op.drop_table('knowledge_versions')
    # ### end Alembic commands ###
