"""expand phase3 tables

Revision ID: 20260806phase3
Revises: 20260806catalog
Create Date: 2026-08-06 10:17:16.691613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260806phase3'
down_revision: Union[str, None] = '20260806catalog'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('knowledge_version_id', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_version_id'], ['knowledge_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_version_id', 'source_path', name='uq_knowledge_sources_version_path')
    )
    op.create_index(op.f('ix_knowledge_sources_knowledge_version_id'), 'knowledge_sources', ['knowledge_version_id'], unique=False)
    op.create_table('knowledge_units',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('knowledge_version_id', sa.String(length=64), nullable=False),
    sa.Column('unit_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category_path', sa.JSON(), nullable=False),
    sa.Column('semantic_key', sa.String(length=1024), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('can_use_for_quiz', sa.Boolean(), nullable=False),
    sa.Column('can_use_for_scenario', sa.Boolean(), nullable=False),
    sa.Column('can_use_for_evaluation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_version_id'], ['knowledge_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_version_id', 'unit_key', name='uq_knowledge_units_version_key')
    )
    op.create_index(op.f('ix_knowledge_units_content_hash'), 'knowledge_units', ['content_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_units_knowledge_version_id'), 'knowledge_units', ['knowledge_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_units_semantic_key'), 'knowledge_units', ['semantic_key'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_set_id', sa.String(length=64), nullable=False),
    sa.Column('knowledge_version_id', sa.String(length=64), nullable=False),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_version_id'], ['knowledge_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quiz_set_id'], ['quiz_sets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_knowledge_version_id'), 'quiz_attempts', ['knowledge_version_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_learner_id'), 'quiz_attempts', ['learner_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_quiz_set_id'), 'quiz_attempts', ['quiz_set_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_status'), 'quiz_attempts', ['status'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('quiz_attempt_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('selected_answers', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_attempt_id', 'question_id', name='uq_quiz_answers_attempt_question')
    )
    op.create_index(op.f('ix_quiz_answers_question_id'), 'quiz_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_quiz_attempt_id'), 'quiz_answers', ['quiz_attempt_id'], unique=False)
    with op.batch_alter_table('knowledge_versions') as batch_op:
        batch_op.add_column(sa.Column('version_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('schema_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_root', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('coverage', sa.JSON(), nullable=True))
    op.execute("UPDATE knowledge_versions SET schema_version = 1, source_root = '', coverage = '{}'")
    with op.batch_alter_table('knowledge_versions') as batch_op:
        batch_op.alter_column('schema_version', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('source_root', existing_type=sa.String(length=1024), nullable=False)
        batch_op.alter_column('coverage', existing_type=sa.JSON(), nullable=False)
    op.create_index(op.f('ix_knowledge_versions_version_hash'), 'knowledge_versions', ['version_hash'], unique=True)
    with op.batch_alter_table('questions') as batch_op:
        batch_op.add_column(sa.Column('knowledge_unit_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
    op.execute("UPDATE questions SET explanation = '', category = '', difficulty = 'easy', position = 0")
    with op.batch_alter_table('questions') as batch_op:
        batch_op.alter_column('explanation', existing_type=sa.Text(), nullable=False)
        batch_op.alter_column('category', existing_type=sa.String(length=128), nullable=False)
        batch_op.alter_column('difficulty', existing_type=sa.String(length=32), nullable=False)
        batch_op.alter_column('position', existing_type=sa.Integer(), nullable=False)
    op.create_index(op.f('ix_questions_knowledge_unit_id'), 'questions', ['knowledge_unit_id'], unique=False)
    with op.batch_alter_table('questions') as batch_op:
        batch_op.create_foreign_key(
            'fk_questions_knowledge_unit_id',
            'knowledge_units',
            ['knowledge_unit_id'],
            ['id'],
            ondelete='RESTRICT',
        )
    with op.batch_alter_table('quiz_sets') as batch_op:
        batch_op.add_column(sa.Column('quiz_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('passing_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE quiz_sets SET passing_score = 80")
    with op.batch_alter_table('quiz_sets') as batch_op:
        batch_op.alter_column('passing_score', existing_type=sa.Integer(), nullable=False)
    op.create_index(op.f('ix_quiz_sets_quiz_hash'), 'quiz_sets', ['quiz_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_sets_quiz_hash'), table_name='quiz_sets')
    op.drop_column('quiz_sets', 'published_at')
    op.drop_column('quiz_sets', 'passing_score')
    op.drop_column('quiz_sets', 'quiz_hash')
    with op.batch_alter_table('questions') as batch_op:
        batch_op.drop_constraint('fk_questions_knowledge_unit_id', type_='foreignkey')
    op.drop_index(op.f('ix_questions_knowledge_unit_id'), table_name='questions')
    op.drop_column('questions', 'position')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'category')
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'knowledge_unit_id')
    op.drop_index(op.f('ix_knowledge_versions_version_hash'), table_name='knowledge_versions')
    op.drop_column('knowledge_versions', 'coverage')
    op.drop_column('knowledge_versions', 'source_root')
    op.drop_column('knowledge_versions', 'schema_version')
    op.drop_column('knowledge_versions', 'version_hash')
    op.drop_index(op.f('ix_quiz_answers_quiz_attempt_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_question_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_quiz_attempts_status'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_set_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_learner_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_knowledge_version_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_knowledge_units_semantic_key'), table_name='knowledge_units')
    op.drop_index(op.f('ix_knowledge_units_knowledge_version_id'), table_name='knowledge_units')
    op.drop_index(op.f('ix_knowledge_units_content_hash'), table_name='knowledge_units')
    op.drop_table('knowledge_units')
    op.drop_index(op.f('ix_knowledge_sources_knowledge_version_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
