"""add quiz publication keys

Revision ID: 20260806quizpub
Revises: 20260806phase3
Create Date: 2026-08-06 10:29:09.482261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260806quizpub'
down_revision: Union[str, None] = '20260806phase3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_key', sa.String(length=128), nullable=True))
    op.execute("UPDATE questions SET question_key = id")
    op.create_index(op.f('ix_questions_question_key'), 'questions', ['question_key'], unique=False)
    with op.batch_alter_table('questions') as batch_op:
        batch_op.create_unique_constraint('uq_questions_set_key', ['quiz_set_id', 'question_key'])
    op.add_column('quiz_sets', sa.Column('topic_key', sa.String(length=255), nullable=True))
    op.execute("UPDATE quiz_sets SET topic_key = id")
    op.create_index(op.f('ix_quiz_sets_topic_key'), 'quiz_sets', ['topic_key'], unique=False)
    with op.batch_alter_table('quiz_sets') as batch_op:
        batch_op.create_unique_constraint('uq_quiz_sets_version_topic', ['knowledge_version_id', 'topic_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sets') as batch_op:
        batch_op.drop_constraint('uq_quiz_sets_version_topic', type_='unique')
    op.drop_index(op.f('ix_quiz_sets_topic_key'), table_name='quiz_sets')
    op.drop_column('quiz_sets', 'topic_key')
    with op.batch_alter_table('questions') as batch_op:
        batch_op.drop_constraint('uq_questions_set_key', type_='unique')
    op.drop_index(op.f('ix_questions_question_key'), table_name='questions')
    op.drop_column('questions', 'question_key')
    # ### end Alembic commands ###
